### ISSUE TITLE
Add old releases from GitHub to Curseforge

### ISSUE THREAD

**Issue by h3oCharles** [elytra/Engination#7]
https://www.curseforge.com/minecraft/mc-mods/engination-fabric/files

oh hi, it appears that in the curseforge page there's only a download for MC 1.14, plz add the remaining releases that appear on GitHub to Curseforge. I may or may not be making a modpack with this mod

that's all, thx

**Comment by falkreon** [comment]
You probably don't know Curse's history with the WoW community, but they've saved passwords in plaintext, filled their launchers with insecure flash animations, and allowed compromised launchers to circulate. Their negligence has resulted in many data breaches. Curse launchers are a plague upon this land, and I strongly recommend that you never enter your credentials into one, saved or not.

Because of this, I have never, nor will I ever, made decisions in order to make it easier to make packs through Curse. Sometimes I choose to release there in cases where usage is likely to be direct website downloads, especially for Fabric mods which are hard to discover and impossible to use with the launcher. However, you are *permitted* to include these old Forge versions in a Curse pack, and if I remember correctly, this is one of the projects that prior Curse pack makers have authorized for external inclusion, so you should have no problems doing so.

There exist open-source alternatives whose security can be verified and improved, such as peterix's [MultiMC](https://multimc.org/) and sk89q's [SKCraft Launcher](https://github.com/SKCraft/Launcher). They both have pros and cons, of course - MMC requires you to distribute fat zip files every update, and SKCraft requires a webserver and a big time investment. Definitely use what's right for you, even if it's Curse.

Whew. Now that's out of the way, thanks for dropping me a note, and good luck with your modpack.
